import "./globals.css";
import { Mulish } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import { cn } from "@/lib/utils";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          mulish.className,
          "bg-purple text-white relative overflow-x-hidden"
        )}
      >
        <main className="relative overflow-x-hidden">
          <Navbar />
          {children}
          <Footer />
          <ScrollToTop />
        </main>
      </body>
    </html>
  );
}
